# -*- coding: utf-8 -*-
"""
Created on Mon Aug 13 09:35:16 2018

@author: JG
"""

# -*- coding: utf-8 -*-
"""
Created on Thu Aug  9 23:05:31 2018

@author: JG
"""

import os
import sys
import logging

try:
    import psycopg2 as pg
    import psycopg2.extras
except:
    print( "Install psycopg2")
    exit(123)
    
PG_CONN_STRING = "dbname='postgres' port='5432' user='postgres' password='phludphlud'"
dbconn = pg.connect(PG_CONN_STRING)
cursor = dbconn.cursor()
table_names = ['business', 'checkin', 'photo', 'review', 'tip', 'users']
for tname in table_names:
    cursor.execute("CREATE TABLE " + tname +
                   """
                       (
                       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
                       data jsonb NOT NULL
                       );
               """)

# cursor.fetchone()


dbconn.commit()